export const RouteNames = {
  AuthRoutes: {
    LoginScreen: 'LoginScreen',
    OnBoardingScreen: 'OnBoardingScreen',
    SignUpScreen: 'SignUpScreen',
    RegisterScreen: 'RegisterScreen',
    ForgotPasswordScreen: 'ForgotPasswordScreen',
    OtpScreen: 'OtpScreen',
    SelectLanguage: 'SelectLanguage',
    GoogleSignUp: 'GoogleSignUp',
    VerifyUser: 'VerifyUser',
  },
  HomeRoutes: {
    DrawerStack: 'DrawerStack',
    TabStack: 'TabStack',
    HomeScreen: 'HomeScreen',
    NavigationScreen: 'NavigationScreen',
    NotificationScreen: 'NotificationScreen',
    EditProfileScreen: 'EditProfileScreen',
    ChangePassword: 'ChangePasswrod',
    BlogDetails: 'BlogDetails',
    LiveSession: 'LiveSession',
    CreateService: 'CreateService',
    CreateLead: 'CreateLead',
    Leads: 'Leads',
    ServiceDetail: 'ServiceDetail',
    QuestionsAndAnswers: 'QuestionsAndAnswers',
    WebView: 'WebView',
    CreateQuestion: 'CreateQuestion',
  },
};
